name: wordpress-frankenphp

services:
    dozzle:
        container_name: dozzle
        image: amir20/dozzle:latest
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - dozzle_data:/data
        ports:
            - 8080:8080
    wordpress:
        env_file: ".env"
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./public/wp-config.php:/app/public/wp-config.php:ro
            - ./public/wp-content/db.php:/app/public/wp-content/db.php:ro
            - ./public/wp-content/database:/app/public/wp-content/database
            - ./public/wp-content/uploads:/app/public/wp-content/uploads
            - ./log:/var/log
