zlib.output_compression = Off

opcache.enable=1
opcache.jit_buffer_size=100M
opcache.jit=tracing

error_log = /var/log/error.log
display_errors = Off
log_errors = On

memory_limit = 256M
max_execution_time = 10
allow_url_fopen = Off
upload_max_filesize = 5M
post_max_size = 5M

realpath_cache_size = 16M
realpath_cache_ttl = 120

session.save_handler = files
session.save_path = /var/lib/php/sessions
session.cache_limiter = public
session.cache_expire = 180
